### PR TITLE
#160577432 Setup environment for writing tests

### PR DESCRIPTION
**Pull request by lukorito**
#### What does this PR do?
This PR sets up an environment for testing the Author's Haven front-end application. It also includes settings to test the coverage of the application.
#### Description of Task to be completed?
- Include `Jest` and `Enzyme` as dependencies in the application
- Add a coveralls badge to the Readme
#### How should this be manually tested?
- Clone the github repository `git clone https://github.com/andela/ah-shakas-frontend` on your machine.
- Change your working directory to the project folder `cd ah-shakas-frontend`
- Install the required dependencies using `yarn install`
- This chore can be tested by running tests in the `__tests__` folder inside `src`.
- Create a file with `test.js` extension.
- Run `yarn  coverage`
- This output is expected
```
$ react-scripts test --coverage
 PASS  src/App.test.js
  ✓ renders without crashing (26ms)

------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |     4.65 |        0 |     6.25 |     4.65 |                   |
 App.js           |      100 |      100 |      100 |      100 |                   |
 index.js         |        0 |      100 |      100 |        0 |      1,2,3,4,5,12 |
 serviceWorker.js |        0 |        0 |        0 |        0 |... 19,126,127,128 |
 setupTests.js    |      100 |      100 |      100 |      100 |                   |
------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.474s
Ran all test suites.
✨  Done in 6.00s.
```

#### Any background context you want to provide?
All components should have tests: Unit tests thereafter integration and end to end tests
#### What are the relevant pivotal tracker stories?
[#160577432](https://www.pivotaltracker.com/story/show/160577432)

### CODE REVIEW

**Comment by codingedward** [comment]
@lukorito, this branch needs to be rebased on develop.

**Comment by caveinn** [comment]
@lukorito  I think for the pr comment on the section on how to test manually you should specify how tests should be run. You only state that it should be tested by running tests but don't specify how they can be run.

**Comment by Arthur236** [comment]
@lukorito action the feedback @caveinn has pointed out and the pr will be ready to merge.

**Comment by Arthur236** [comment]
@lukorito kindly fix the conflicts.

Also, could you integrate `Coveralls` for test coverage? Since it's related to our test environment, I don't think it's necessary to open up another chore for it

**Comment by lukorito** [comment]
> @lukorito kindly fix the conflicts.
> 
> Also, could you integrate `Coveralls` for test coverage? Since it's related to our test environment, I don't think it's necessary to open up another chore for it

Alright! Will do

**Comment by lukorito** [comment]
> @lukorito action the feedback @caveinn has pointed out and the pr will be ready to merge.

Noted

**Comment by gloriaodipo** [comment]
@lukorito Just a simple fix, *Run yarn tests* should be *yarn test* instead.

**Comment by lukorito** [comment]
> @lukorito, this branch needs to be rebased on develop.

I have done that

**Comment by Arthur236** [comment]
@lukorito Instead of having to run `yarn test -- -- coverage`, why don't you include a script in the `package.json` file that will only require us to run something like `yarn coverage` to get the same output.

**Review by caveinn — APPROVED** [review]

**Review by gloriaodipo — APPROVED** [review]

**Comment by lukorito** [comment]
> ething like `yarn`
On it

**Comment by lukorito** [comment]
> @lukorito Instead of having to run `yarn test -- -- coverage`, why don't you include a script in the `package.json` file that will only require us to run something like `yarn coverage` to get the same output.

On it

**Review by Arthur236 — APPROVED** [review]
Looks good 👍

**Pull request merged**
